// This file is generated by scripts/generate-runtime-validators.sh — do not edit.
//
// The conditional layer. See scripts/lib/write-conditional-layer.py for what it
// evaluates and why the generated schemas cannot.

import * as z from 'zod';
import * as gen from './zod.gen';

const RULES: Record<string, Rule> = {
  "https://openinherit.org/v3/asset.json": {
    "conditionals": [
      {
        "if": {
          "required": [
            "category"
          ],
          "properties": {
            "category": {
              "const": "financial"
            }
          }
        },
        "then": {
          "$ref": "https://openinherit.org/v3/asset-categories/financial.json"
        }
      },
      {
        "if": {
          "required": [
            "category"
          ],
          "properties": {
            "category": {
              "const": "vehicle"
            }
          }
        },
        "then": {
          "$ref": "https://openinherit.org/v3/asset-categories/vehicle.json"
        }
      },
      {
        "if": {
          "required": [
            "category"
          ],
          "properties": {
            "category": {
              "const": "digital"
            }
          }
        },
        "then": {
          "$ref": "https://openinherit.org/v3/asset-categories/digital.json"
        }
      },
      {
        "if": {
          "required": [
            "category"
          ],
          "properties": {
            "category": {
              "const": "business"
            }
          }
        },
        "then": {
          "$ref": "https://openinherit.org/v3/asset-categories/business.json"
        }
      }
    ],
    "overlays": {
      "netEquity": {
        "properties": {
          "amount": {
            "minimum": 0
          }
        }
      }
    },
    "closed": {
      "props": [
        "accessInstructions",
        "acquisitionType",
        "applicableLaw",
        "assetCollectionId",
        "beneficiaryDesignation",
        "brand",
        "category",
        "comments",
        "communalAuthority",
        "comparableSearchProfile",
        "condition",
        "conditionGrade",
        "conditionStandard",
        "conditionSystem",
        "containedInAssetId",
        "culturalDisposition",
        "custodian",
        "dataProvenance",
        "description",
        "digitalAccessConsent",
        "estimatedValue",
        "externalLinks",
        "fieldProvenance",
        "gemologicalCertificate",
        "id",
        "identifiers",
        "images",
        "inNegativeEquity",
        "includedDocuments",
        "insurance",
        "insuranceCover",
        "lastVerifiedAt",
        "listings",
        "location",
        "mergedInto",
        "mobilityType",
        "model",
        "name",
        "netEquity",
        "notes",
        "originalPackaging",
        "ownerIntent",
        "ownershipEvidence",
        "passesOutsideEstate",
        "possessionStatus",
        "productPage",
        "professionalValuation",
        "propertyId",
        "provenance",
        "provenanceChain",
        "purchaseDate",
        "purchasedFrom",
        "quantity",
        "registrationStatus",
        "searchTerms",
        "serviceHistory",
        "shippingClass",
        "significance",
        "spaceId",
        "spaceIdDisplay",
        "splitFrom",
        "stolenArtCheck",
        "subcategory",
        "successionRegime",
        "suggestedSubcategory",
        "taxReliefEligibility",
        "taxTreatment",
        "urgency",
        "urgencyReason",
        "valuationConfidence",
        "valuationDate",
        "valuationReliability",
        "verifiedBy",
        "visibility"
      ],
      "patterns": [
        "^x-inherit-[a-z][a-z0-9-]{1,54}$"
      ]
    }
  },
  "https://openinherit.org/v3/bequest.json": {
    "conditionals": [
      {
        "if": {
          "required": [
            "bequestType"
          ],
          "properties": {
            "bequestType": {
              "const": "class"
            }
          }
        },
        "then": {
          "required": [
            "classDefinition"
          ]
        }
      },
      {
        "if": {
          "required": [
            "bequestType"
          ],
          "properties": {
            "bequestType": {
              "const": "life_interest"
            }
          }
        },
        "then": {
          "required": [
            "lifeInterest"
          ]
        }
      }
    ],
    "overlays": {},
    "closed": {
      "props": [
        "amount",
        "applicableLaw",
        "assetCollectionId",
        "assetIds",
        "beneficiaryId",
        "beneficiaryIdDisplay",
        "beneficiaryOrganisation",
        "bequestType",
        "charityGiftAidEligible",
        "charityNonMergingClause",
        "charityPurposeRestriction",
        "charityRegistrationVerifiedAt",
        "charityReportingRequired",
        "classDefinition",
        "classSubstitution",
        "clauseReference",
        "comments",
        "conditions",
        "constrainedBy",
        "customaryOverride",
        "description",
        "distributionMethod",
        "executorDirections",
        "giftAidRegistrationNumber",
        "giftAidVerificationUrl",
        "giftAidVerifiedAt",
        "hotchpot",
        "hotchpotTransferIds",
        "id",
        "inheritanceResponse",
        "insurancePolicyIds",
        "legacyPledge",
        "liabilityIds",
        "lifeInterest",
        "mentionedAssetIds",
        "mentionedPropertyIds",
        "notes",
        "postDeathActions",
        "powerOfAppointmentId",
        "precatoryWishes",
        "predeceaseRule",
        "priority",
        "propertyIds",
        "provenance",
        "sharePercentage",
        "sourceAssetId",
        "substitutions",
        "visibility"
      ],
      "patterns": [
        "^x-inherit-[a-z][a-z0-9-]{1,54}$"
      ]
    }
  },
  "https://openinherit.org/v3/catalogue.json": {
    "conditionals": [],
    "overlays": {
      "conformance": {
        "properties": {
          "profile": {
            "const": "catalogue"
          }
        }
      }
    },
    "closed": {
      "props": [
        "$schema",
        "@context",
        "assetCollections",
        "assetInterests",
        "assets",
        "auditLog",
        "changeDescription",
        "completeness",
        "conformance",
        "conformanceProfile",
        "dataProvenance",
        "dealerInterests",
        "documentVersion",
        "exportedAt",
        "exportedBy",
        "generator",
        "giftListSettings",
        "importSources",
        "insurancePolicies",
        "legacyContacts",
        "legacyLetter",
        "organisations",
        "previousVersionId",
        "properties",
        "recommendedActions",
        "schemaVersion",
        "spaces",
        "valuations",
        "versionedAt",
        "wishes"
      ],
      "patterns": [
        "^x-inherit-[a-z][a-z0-9-]{1,54}$"
      ]
    }
  },
  "https://openinherit.org/v3/estate.json": {
    "conditionals": [],
    "overlays": {
      "netEstateEquity": {
        "properties": {
          "amount": {
            "minimum": 0
          }
        }
      }
    },
    "closed": {
      "props": [
        "adjudicatingBodies",
        "administration",
        "administrationDeadline",
        "administrationDeadlineSource",
        "administrationPhases",
        "ancillaryProbate",
        "attestation",
        "careProvisions",
        "choiceOfLaw",
        "codicils",
        "commorientesRule",
        "companionEstateId",
        "companionLinkStatus",
        "connections",
        "constructionClauses",
        "contestability",
        "conversionRates",
        "createdAt",
        "deathCertificateDate",
        "deathCertificateReference",
        "deathRecord",
        "deathVerification",
        "decoupledAt",
        "defaultPropertyRegime",
        "defaultSuccessionRegime",
        "disinheritedPersons",
        "domicile",
        "electiveShareRight",
        "escheatment",
        "executionDate",
        "executorPowers",
        "externalReferences",
        "familyProvisionClaims",
        "forcedHeirship",
        "governingJurisdictions",
        "id",
        "integrity",
        "judicialVariationPower",
        "jurisdictionRules",
        "lastModifiedAt",
        "linkedAt",
        "mirrorWillId",
        "mutualWillAgreement",
        "netEstateEquity",
        "noContestClause",
        "notes",
        "parallelDistributions",
        "parallelSuccessionConflicts",
        "pretermittedHeirClaims",
        "primaryInstrument",
        "priorMatrimonialClaim",
        "probateGrant",
        "probateReadiness",
        "provenance",
        "registrations",
        "religiousConsideration",
        "reportingCurrency",
        "revocationClause",
        "revokesDocumentIds",
        "status",
        "statutoryExclusions",
        "successionConflicts",
        "suggestedPractitionerNeeds",
        "taxTreaties",
        "taxTreatyPositions",
        "testamentaryCapacity",
        "testamentaryPromises",
        "testamentaryScenarios",
        "testatorPersonId",
        "testatorPersonIdDisplay",
        "totalEstimatedValue",
        "validityStatus",
        "willType"
      ],
      "patterns": [
        "^x-inherit-[a-z][a-z0-9-]{1,54}$"
      ]
    }
  },
  "https://openinherit.org/v3/property.json": {
    "conditionals": [],
    "overlays": {
      "netEquity": {
        "properties": {
          "amount": {
            "minimum": 0
          }
        }
      }
    },
    "closed": {
      "props": [
        "acquisitionType",
        "address",
        "applicableLaw",
        "characterClassification",
        "comments",
        "communalAuthority",
        "culturalDisposition",
        "custodianPersonId",
        "custodianPersonIdDisplay",
        "epc",
        "estimatedValue",
        "externalLinks",
        "fieldProvenance",
        "floodRisk",
        "governmentConsentRequired",
        "homesteadStatus",
        "id",
        "images",
        "inNegativeEquity",
        "isPrimaryResidence",
        "landRegistry",
        "leasehold",
        "mobilityType",
        "mortgageOutstanding",
        "name",
        "netEquity",
        "notes",
        "ownershipEvidence",
        "ownershipModel",
        "ownershipPercentage",
        "ownershipType",
        "passesOutsideEstate",
        "professionalValuation",
        "propertyType",
        "provenance",
        "registrationStatus",
        "rentalIncome",
        "statutoryLifeEstate",
        "successionRegime",
        "taxReliefEligibility",
        "taxTreatment",
        "tenureType",
        "valuationConfidence",
        "valuationDate",
        "visibility"
      ],
      "patterns": [
        "^x-inherit-[a-z][a-z0-9-]{1,54}$"
      ]
    }
  },
  "https://openinherit.org/v3/proxy-authorisation.json": {
    "conditionals": [
      {
        "if": {
          "required": [
            "delegateType"
          ],
          "properties": {
            "delegateType": {
              "const": "person"
            }
          }
        },
        "then": {
          "required": [
            "proxyPersonId"
          ]
        }
      },
      {
        "if": {
          "required": [
            "delegateType"
          ],
          "properties": {
            "delegateType": {
              "const": "agent"
            }
          }
        },
        "then": {
          "required": [
            "agentId"
          ]
        }
      },
      {
        "if": {
          "required": [
            "delegateType"
          ],
          "properties": {
            "delegateType": {
              "const": "organisation"
            }
          }
        },
        "then": {
          "required": [
            "proxyPersonId"
          ]
        }
      }
    ],
    "overlays": {},
    "closed": {
      "props": [
        "activationDate",
        "activationTrigger",
        "activationVerificationMethod",
        "activationVerifiedAt",
        "activationVerifiedBy",
        "agentCapabilities",
        "agentId",
        "agentIdDisplay",
        "auditLog",
        "auditTrailEnabled",
        "authenticationMethod",
        "consentRecord",
        "credentialRef",
        "dealerNegotiationPermitted",
        "delegateType",
        "delegationConstraints",
        "delegationType",
        "expiryDate",
        "externalConsentRef",
        "healthcareRecordAccess",
        "id",
        "notes",
        "provenance",
        "proxyPersonId",
        "proxyPersonIdDisplay",
        "revocation",
        "revocationDate",
        "scope",
        "startDate",
        "subDelegation",
        "testatorPersonId",
        "testatorPersonIdDisplay"
      ],
      "patterns": [
        "^x-inherit-[a-z][a-z0-9-]{1,54}$"
      ]
    }
  },
  "https://openinherit.org/v3/schema.json": {
    "conditionals": [
      {
        "if": {
          "required": [
            "conformanceProfile"
          ],
          "properties": {
            "conformanceProfile": {
              "const": "catalogue"
            }
          }
        },
        "then": {
          "$ref": "https://openinherit.org/v3/catalogue.json"
        },
        "else": {
          "required": [
            "schemaVersion",
            "estate",
            "people"
          ],
          "properties": {
            "assets": {
              "maxItems": 2000
            },
            "assetCollections": {
              "maxItems": 200
            },
            "valuations": {
              "maxItems": 5000
            },
            "wishes": {
              "maxItems": 100
            },
            "importSources": {
              "maxItems": 50
            },
            "insurancePolicies": {
              "maxItems": 50
            },
            "$schema": {
              "const": "https://openinherit.org/v3/schema.json"
            },
            "conformance": {
              "properties": {
                "profile": {
                  "const": "estate"
                }
              }
            }
          }
        }
      }
    ],
    "overlays": {},
    "closed": {
      "props": [
        "$schema",
        "@context",
        "@type",
        "applicationState",
        "assetCollections",
        "assets",
        "auditLog",
        "bequests",
        "bundleType",
        "changeDescription",
        "conformance",
        "conformanceProfile",
        "dataProvenance",
        "documentVersion",
        "documents",
        "estate",
        "executors",
        "exportedAt",
        "exportedBy",
        "extensions",
        "generator",
        "guardians",
        "importSources",
        "insurancePolicies",
        "integrity",
        "kinships",
        "liabilities",
        "lifetimeTransfers",
        "nonprobateTransfers",
        "organisations",
        "partialDocument",
        "people",
        "pets",
        "powersOfAppointment",
        "previousVersionId",
        "properties",
        "proxyAuthorisations",
        "referentialIntegrity",
        "relationships",
        "schemaVersion",
        "spaces",
        "trusts",
        "valuations",
        "versionedAt",
        "wishes",
        "x-inherit-africa-customary",
        "x-inherit-australia-nz",
        "x-inherit-brazil",
        "x-inherit-canada",
        "x-inherit-eu-succession",
        "x-inherit-hindu-succession",
        "x-inherit-hong-kong",
        "x-inherit-india",
        "x-inherit-ireland",
        "x-inherit-islamic-succession",
        "x-inherit-israel",
        "x-inherit-japan",
        "x-inherit-jewish-succession",
        "x-inherit-latin-america",
        "x-inherit-prc-china",
        "x-inherit-scotland",
        "x-inherit-singapore-malaysia",
        "x-inherit-switzerland",
        "x-inherit-uae",
        "x-inherit-uk-england-wales",
        "x-inherit-us-estate"
      ],
      "patterns": [
        "^x-inherit-[a-z][a-z0-9-]{1,54}$"
      ]
    }
  }
};

const REFKEYS: Record<string, { props: string[]; patterns: string[] }> = {
  "https://openinherit.org/v3/asset-categories/business.json": {
    "props": [
      "businessInterest",
      "coOwnership",
      "intellectualProperty",
      "stockCompensation"
    ],
    "patterns": []
  },
  "https://openinherit.org/v3/asset-categories/digital.json": {
    "props": [
      "cloudStorage",
      "cryptoAccess",
      "digitalAccess",
      "domainNameAccess",
      "fiduciaryAccess",
      "gamingAccess",
      "loyaltyAccess",
      "monetisedContentAccess",
      "nftAccess",
      "platformDelegation",
      "socialMedia"
    ],
    "patterns": []
  },
  "https://openinherit.org/v3/asset-categories/financial.json": {
    "props": [
      "businessInterest",
      "coOwnership",
      "debtReceivable",
      "insurancePolicy",
      "intellectualProperty",
      "pension",
      "shareholding",
      "stockCompensation"
    ],
    "patterns": []
  },
  "https://openinherit.org/v3/asset-categories/vehicle.json": {
    "props": [
      "vehicle",
      "vehicleCheck"
    ],
    "patterns": []
  },
  "https://openinherit.org/v3/catalogue.json": {
    "props": [
      "$schema",
      "@context",
      "assetCollections",
      "assetInterests",
      "assets",
      "auditLog",
      "changeDescription",
      "completeness",
      "conformance",
      "conformanceProfile",
      "dataProvenance",
      "dealerInterests",
      "documentVersion",
      "exportedAt",
      "exportedBy",
      "generator",
      "giftListSettings",
      "importSources",
      "insurancePolicies",
      "legacyContacts",
      "legacyLetter",
      "organisations",
      "previousVersionId",
      "properties",
      "recommendedActions",
      "schemaVersion",
      "spaces",
      "valuations",
      "versionedAt",
      "wishes"
    ],
    "patterns": [
      "^x-inherit-[a-z][a-z0-9-]{1,54}$"
    ]
  }
};

type Rule = { conditionals: any[]; overlays: Record<string, any>; closed: { props: string[]; patterns: string[] } | null };
type Issue = { path: (string | number)[]; message: string };

const isObj = (v: unknown): v is Record<string, unknown> => v !== null && typeof v === 'object' && !Array.isArray(v);
const canon = (v: unknown): unknown => Array.isArray(v) ? v.map(canon)
  : isObj(v) ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, canon(v[k])])) : v;
const same = (a: unknown, b: unknown) => JSON.stringify(canon(a)) === JSON.stringify(canon(b));

function evaluate(s: any, v: unknown, path: (string | number)[], out: Issue[]): void {
  if (s.$ref !== undefined) {
    const r = byId(s.$ref).safeParse(v);
    if (!r.success) for (const i of r.error.issues) out.push({ path: [...path, ...(i.path as (string | number)[])], message: i.message });
  }
  if (s.const !== undefined && !same(v, s.const)) out.push({ path, message: `must be ${JSON.stringify(s.const)}` });
  if (s.enum !== undefined && !s.enum.some((e: unknown) => same(v, e))) out.push({ path, message: `must be one of ${JSON.stringify(s.enum)}` });
  if (typeof v === 'number') {
    if (s.minimum !== undefined && v < s.minimum) out.push({ path, message: `must be >= ${s.minimum}` });
    if (s.maximum !== undefined && v > s.maximum) out.push({ path, message: `must be <= ${s.maximum}` });
    if (s.exclusiveMinimum !== undefined && v <= s.exclusiveMinimum) out.push({ path, message: `must be > ${s.exclusiveMinimum}` });
    if (s.exclusiveMaximum !== undefined && v >= s.exclusiveMaximum) out.push({ path, message: `must be < ${s.exclusiveMaximum}` });
  }
  if (Array.isArray(v)) {
    if (s.maxItems !== undefined && v.length > s.maxItems) out.push({ path, message: `must have at most ${s.maxItems} items` });
    if (s.minItems !== undefined && v.length < s.minItems) out.push({ path, message: `must have at least ${s.minItems} items` });
    if (s.contains !== undefined && !v.some((x) => passes(s.contains, x))) out.push({ path, message: 'must contain a matching item' });
  }
  if (isObj(v)) {
    for (const k of s.required ?? []) if (!(k in v)) out.push({ path: [...path, k], message: `required: ${k}` });
    for (const [k, sub] of Object.entries(s.properties ?? {})) if (k in v) evaluate(sub, v[k], [...path, k], out);
  }
  for (const sub of s.allOf ?? []) evaluate(sub, v, path, out);
  if (s.not !== undefined && passes(s.not, v)) out.push({ path, message: 'must not match the excluded shape' });
  if (s.if !== undefined) {
    const branch = passes(s.if, v) ? s.then : s.else;
    if (branch !== undefined) evaluate(branch, v, path, out);
  }
}

function passes(s: any, v: unknown): boolean {
  const out: Issue[] = [];
  evaluate(s, v, [], out);
  return out.length === 0;
}

/** Member names a branch evaluates, for unevaluatedProperties. */
function evaluated(s: any, names: Set<string>, patterns: string[]): void {
  for (const k of Object.keys(s.properties ?? {})) names.add(k);
  if (s.$ref !== undefined) {
    const k = REFKEYS[s.$ref];
    for (const p of k.props) names.add(p);
    patterns.push(...k.patterns);
  }
  for (const sub of s.allOf ?? []) evaluated(sub, names, patterns);
}

function check(id: string, v: unknown): Issue[] {
  const rule: Rule = RULES[id];
  const out: Issue[] = [];
  if (!isObj(v)) return out;
  const names = new Set<string>(rule.closed?.props ?? []);
  const patterns = [...(rule.closed?.patterns ?? [])];
  for (const c of rule.conditionals) {
    const ok = passes(c.if, v);
    const branch = ok ? c.then : c.else;
    if (ok) evaluated(c.if, names, patterns);
    if (branch !== undefined) {
      evaluate(branch, v, [], out);
      evaluated(branch, names, patterns);
    }
  }
  for (const [k, sub] of Object.entries(rule.overlays)) if (k in v) evaluate(sub, v[k], [k], out);
  if (rule.closed) {
    const res = patterns.map((p) => new RegExp(p, 'u'));
    for (const k of Object.keys(v)) {
      if (!names.has(k) && !res.some((r) => r.test(k))) out.push({ path: [k], message: `${k} is not allowed here (unevaluatedProperties)` });
    }
  }
  return out;
}

const layer = <T extends z.ZodType>(id: string, base: T) =>
  z.intersection(base, z.unknown().superRefine((v, ctx) => {
    for (const i of check(id, v)) ctx.addIssue({ code: 'custom', path: i.path, message: i.message });
  }));

export const zAsset = layer('https://openinherit.org/v3/asset.json', gen.zAsset);
export const zBequest = layer('https://openinherit.org/v3/bequest.json', gen.zBequest);
export const zCatalogue = layer('https://openinherit.org/v3/catalogue.json', gen.zCatalogue);
export const zEstate = layer('https://openinherit.org/v3/estate.json', gen.zEstate);
export const zProperty = layer('https://openinherit.org/v3/property.json', gen.zProperty);
export const zProxyAuthorisation = layer('https://openinherit.org/v3/proxy-authorisation.json', gen.zProxyAuthorisation);
export const zSchema = layer('https://openinherit.org/v3/schema.json', gen.zSchema);

function byId(id: string): z.ZodType {
  switch (id) {
    case 'https://openinherit.org/v3/asset-categories/business.json': return gen.zBusiness;
    case 'https://openinherit.org/v3/asset-categories/digital.json': return gen.zDigital;
    case 'https://openinherit.org/v3/asset-categories/financial.json': return gen.zFinancial;
    case 'https://openinherit.org/v3/asset-categories/vehicle.json': return gen.zVehicle;
    case 'https://openinherit.org/v3/catalogue.json': return zCatalogue;
  }
  throw new Error(`conditional layer: no validator for ${id}`);
}
