// SPDX-License-Identifier: CC0-1.0

/**
 * validate-document.ts — Three-level INHERIT document validator.
 *
 * Demonstrates:
 *   - Level 1: JSON Schema validation with Blaze (pre-compiled 2020-12 template)
 *   - Level 2: Referential integrity checks across entity arrays
 *   - Level 3: Placeholder for extension-specific field checking
 *
 * Run:  npx tsx validate-document.ts <path-to-inherit-json>
 *       pnpm run validate -- <path-to-inherit-json>
 *
 * Exit code 0 if Level 2 passes, 1 otherwise.
 *
 * Note: Blaze returns pass/fail only — it does not provide detailed error
 * paths like AJV did. For diagnostic detail, use the Sourcemeta CLI:
 *   jsonschema validate instance.json ../v3/schema.json --resolve ../v3/
 */

import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { Blaze } from "@sourcemeta/blaze";

// ---------------------------------------------------------------------------
// Types — minimal shapes for the cross-reference checks
// ---------------------------------------------------------------------------

/** Any entity with an `id` field. */
interface Identifiable {
  id: string;
}

/** Minimal shape of the root INHERIT document for referential integrity. */
interface InheritDocument {
  estate: {
    testatorPersonId: string;
    [key: string]: unknown;
  };
  people: Identifiable[];
  assets: Identifiable[];
  bequests: Array<{
    id: string;
    beneficiaryId?: string;
    sourceAssetId?: string;
    [key: string]: unknown;
  }>;
  executors: Array<{
    id: string;
    personId: string;
    [key: string]: unknown;
  }>;
  guardians: Array<{
    id: string;
    personId: string;
    childPersonId: string;
    [key: string]: unknown;
  }>;
  [key: string]: unknown;
}

/** A referential integrity error. */
interface RefError {
  path: string;
  message: string;
  explanation: string;
}

// ---------------------------------------------------------------------------
// CLI argument handling
// ---------------------------------------------------------------------------

const filePath = process.argv[2];

if (!filePath) {
  console.error("Usage: npx tsx validate-document.ts <path-to-inherit-json>");
  console.error("Example: npx tsx validate-document.ts ../examples/fixtures/english-family-estate.json");
  process.exit(1);
}

const resolvedPath = resolve(filePath);

// ---------------------------------------------------------------------------
// 1. Load and parse the input document
// ---------------------------------------------------------------------------

let rawJson: string;
try {
  rawJson = readFileSync(resolvedPath, "utf-8");
} catch (err) {
  const msg = err instanceof Error ? err.message : String(err);
  console.error(`ERROR: Could not read file: ${msg}`);
  process.exit(1);
}

let document: Record<string, unknown>;
try {
  document = JSON.parse(rawJson);
} catch (err) {
  const msg = err instanceof Error ? err.message : String(err);
  console.error(`ERROR: Invalid JSON: ${msg}`);
  console.error("\nConformance level: 0 (not valid JSON)");
  process.exit(1);
}

// ---------------------------------------------------------------------------
// 2. Level 1: JSON Schema validation (Blaze, pre-compiled 2020-12 template)
// ---------------------------------------------------------------------------

function runLevel1(doc: Record<string, unknown>): { valid: boolean } {
  // Load the pre-compiled template (generated by `pnpm run precompile`)
  const templatePath = join(import.meta.dirname!, "compiled", "schema-template.json");
  const template = JSON.parse(readFileSync(templatePath, "utf-8"));
  const evaluator = new Blaze(template);

  // Blaze returns true/false — no detailed error paths available at runtime.
  // For diagnostic detail, use the Sourcemeta CLI directly:
  //   jsonschema validate instance.json ../v3/schema.json --resolve ../v3/
  const valid = evaluator.validate(doc);
  return { valid };
}

// ---------------------------------------------------------------------------
// 3. Level 2: Referential integrity checks
// ---------------------------------------------------------------------------

function runLevel2(doc: InheritDocument): { valid: boolean; errors: RefError[] } {
  const errors: RefError[] = [];

  // Build lookup sets for people and assets
  const personIds = new Set(doc.people.map((p) => p.id));
  const assetIds = new Set(doc.assets.map((a) => a.id));

  // --- estate.testatorPersonId must reference a person ---
  if (!personIds.has(doc.estate.testatorPersonId)) {
    errors.push({
      path: "/estate/testatorPersonId",
      message: `Person "${doc.estate.testatorPersonId}" not found in people array.`,
      explanation:
        "The testator identified in the estate record must exist as a person in the people array.",
    });
  }

  // --- bequest.beneficiaryId must reference a person (when present) ---
  for (let i = 0; i < doc.bequests.length; i++) {
    const bequest = doc.bequests[i];

    if (bequest.beneficiaryId && !personIds.has(bequest.beneficiaryId)) {
      errors.push({
        path: `/bequests/${i}/beneficiaryId`,
        message: `Person "${bequest.beneficiaryId}" not found in people array.`,
        explanation:
          `Bequest "${bequest.id}" references a beneficiary that does not exist in the people array.`,
      });
    }

    // --- bequest.sourceAssetId must reference an asset (when present) ---
    if (bequest.sourceAssetId && !assetIds.has(bequest.sourceAssetId)) {
      errors.push({
        path: `/bequests/${i}/sourceAssetId`,
        message: `Asset "${bequest.sourceAssetId}" not found in assets array.`,
        explanation:
          `Bequest "${bequest.id}" references a source asset (for demonstrative bequests) that does not exist in the assets array.`,
      });
    }
  }

  // --- executor.personId must reference a person ---
  for (let i = 0; i < doc.executors.length; i++) {
    const executor = doc.executors[i];

    if (!personIds.has(executor.personId)) {
      errors.push({
        path: `/executors/${i}/personId`,
        message: `Person "${executor.personId}" not found in people array.`,
        explanation:
          `Executor "${executor.id}" references a person that does not exist in the people array.`,
      });
    }
  }

  // --- guardian.personId and guardian.childPersonId must reference people ---
  for (let i = 0; i < doc.guardians.length; i++) {
    const guardian = doc.guardians[i];

    if (!personIds.has(guardian.personId)) {
      errors.push({
        path: `/guardians/${i}/personId`,
        message: `Person "${guardian.personId}" not found in people array.`,
        explanation:
          `Guardian "${guardian.id}" references a guardian person that does not exist in the people array.`,
      });
    }

    if (!personIds.has(guardian.childPersonId)) {
      errors.push({
        path: `/guardians/${i}/childPersonId`,
        message: `Person "${guardian.childPersonId}" not found in people array.`,
        explanation:
          `Guardian "${guardian.id}" references a child person that does not exist in the people array.`,
      });
    }
  }

  return { valid: errors.length === 0, errors };
}

// ---------------------------------------------------------------------------
// 4. Main — run all validation levels and report
// ---------------------------------------------------------------------------

function main(): void {
  console.log(`Validating: ${resolvedPath}\n`);
  console.log("=".repeat(60));

  // ---- Level 1: JSON Schema ----
  console.log("\nLevel 1: JSON Schema Validation (Blaze, 2020-12 dialect)");
  console.log("-".repeat(60));

  const level1 = runLevel1(document);

  if (level1.valid) {
    console.log("  PASS — Document conforms to the INHERIT v2 root schema.\n");
  } else {
    console.log("  FAIL — Document does not conform to the INHERIT v2 root schema.");
    console.log("  (Blaze provides pass/fail only. For detailed errors, run:)");
    console.log("  jsonschema validate <file> ../v3/schema.json --resolve ../v3/\n");
    console.log("=".repeat(60));
    console.log("\nConformance level achieved: 0");
    console.log("The document does not pass JSON Schema validation.");
    process.exit(1);
  }

  // ---- Level 2: Referential integrity ----
  console.log("Level 2: Referential Integrity Checks");
  console.log("-".repeat(60));

  const level2 = runLevel2(document as unknown as InheritDocument);

  if (level2.valid) {
    console.log("  PASS — All cross-references resolve correctly.\n");
  } else {
    console.log("  FAIL — Referential integrity errors:\n");
    for (const err of level2.errors) {
      console.log(`  Path:        ${err.path}`);
      console.log(`  Message:     ${err.message}`);
      console.log(`  Explanation: ${err.explanation}`);
      console.log();
    }
    console.log("=".repeat(60));
    console.log("\nConformance level achieved: 1");
    console.log("The document passes schema validation but has broken cross-references.");
    process.exit(1);
  }

  // ---- Level 3: Extension-specific checks (placeholder) ----
  console.log("Level 3: Extension-Specific Field Checking");
  console.log("-".repeat(60));
  console.log("  Level 3 checking not yet implemented — extension-specific field checking is planned.\n");

  // ---- Summary ----
  console.log("=".repeat(60));
  console.log("\nConformance level achieved: 2");
  console.log("The document passes schema validation and referential integrity checks.");
  process.exit(0);
}

main();
