#!/usr/bin/env python3
"""Emit the conditional layer for both generated runtime validators.

The Zod and pydantic generators drop three things that v3/ relies on:

  1. an `if` / `then` / `else` keyed on one member's const value: a
     discriminator, such as the root's `conformanceProfile`;
  2. validation keywords next to a `$ref`, such as catalogue.json's
     `conformance: {$ref, properties: {profile: {const: "catalogue"}}}`;
  3. `unevaluatedProperties: false`, wherever (1) decides which members are
     evaluated.

Without this layer, a regenerated root validator accepts a document with no
`estate`, `people` or `schemaVersion`. This script reads the v3/ sources and
compiles exactly those constructs into rule data. It emits that data, with a
small evaluator, into each validator:

  zod       packages/sdk/src/zod/conditionals.ts holds the rules and the
            evaluator. zod.gen.ts is rewritten so that each affected schema,
            straight after its generated definition, becomes an intersection
            with a superRefine under its own name. Every later reference
            (a parent's items, a nested member, index.ts) then gets the
            layered schema, at any depth, the way pydantic's class
            validators apply wherever a class is used.
  pydantic  packages/sdk-python/openinherit/models.py. Each affected class
            gains a model_validator(mode="after"). It checks the instance's
            JSON dump: by alias, unset members excluded, extras included. That
            is the members the document supplied. Not "before" or "wrap":
            under validate_json(strict=True), the dict those hand back is
            re-validated as Python input, which refuses ISO date strings.
            pydantic also discards, before any validator sees it, an input key
            equal to the Python name of an aliased field (field_schema for
            $schema). For a closed class, its __pydantic_validator__ is
            wrapped so those keys are refused on the raw input first.

Both evaluators also refuse null for any top-level member whose schema
cannot be null. The generated pydantic fields for members a branch requires
are Optional, and "present" must not be satisfied by null.

Inside a branch or overlay, the layer evaluates only: required, const, enum,
minItems, maxItems, minimum, maximum, exclusiveMinimum, exclusiveMaximum,
properties, allOf, not, contains, if/then/else, and $ref to a whole v3 document
schema. A $ref is delegated to that schema's own
(layered) validator. Annotations are ignored. Any other keyword in those
positions is a hard failure, so a construct the layer cannot evaluate can
never be dropped silently.

Usage: write-conditional-layer.py zod <openapi-bundled.yaml> <zod output dir>
       write-conditional-layer.py pydantic <openapi-bundled.yaml> <models.py>
"""
import json
import re
from pprint import pformat
import sys
from pathlib import Path
from urllib.parse import urljoin

import yaml

HEADER = "This file is generated by scripts/generate-runtime-validators.sh — do not edit."
ROOT = Path(__file__).resolve().parents[2]

ANNOTATIONS = {
    "$comment", "description", "title", "examples", "default", "deprecated",
    "readOnly", "writeOnly", "$id", "$schema", "x-inherit-pii",
}
SUPPORTED = {
    "required", "const", "enum", "minItems", "maxItems", "properties",
    "allOf", "not", "contains", "if", "then", "else", "$ref",
    "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum",
}
APPLICATORS = ("allOf", "anyOf", "oneOf", "if", "then", "else", "dependentSchemas", "$ref")


def fail(msg: str) -> None:
    print(f"write-conditional-layer: {msg}", file=sys.stderr)
    sys.exit(1)


def pascal(key: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[^A-Za-z0-9]+", key) if p)


def components(bundle: Path) -> dict[str, str]:
    """$id -> generated name stem, for every bundle component that has an $id."""
    schemas = yaml.safe_load(bundle.read_text())["components"]["schemas"]
    return {b["$id"]: pascal(k) for k, b in schemas.items() if isinstance(b, dict) and b.get("$id")}


def sources() -> dict[str, dict]:
    out = {}
    for f in sorted((ROOT / "v3").rglob("*.json")):
        try:
            doc = json.loads(f.read_text())
        except json.JSONDecodeError:
            continue
        if isinstance(doc, dict) and isinstance(doc.get("$id"), str):
            out[doc["$id"]] = doc
    return out


def is_discriminator(cond: dict) -> bool:
    """if: {required: [p], properties: {p: {const: v}}}, the only `if` shape compiled."""
    s = cond.get("if")
    if not isinstance(s, dict) or set(s) - {"required", "properties"} or "properties" not in s:
        return False
    props = s["properties"]
    if len(props) != 1:
        return False
    (p, sub), = props.items()
    return isinstance(sub, dict) and set(sub) == {"const"} and s.get("required", [p]) == [p]


class Compiler:
    def __init__(self, ids: dict[str, str], srcs: dict[str, dict]):
        self.ids, self.srcs, self.refs = ids, srcs, set()

    def compile(self, s, base: str, where: str):
        if s is True or s is None:
            return {}
        if not isinstance(s, dict):
            fail(f"{where}: cannot evaluate {s!r}")
        out = {}
        for k, v in s.items():
            if k in ANNOTATIONS:
                continue
            if k not in SUPPORTED:
                fail(f"{where}: keyword {k!r} is not one the layer evaluates. Extend the layer, or restructure the schema")
            if k == "$ref":
                target = urljoin(base, v)
                if "#" in target or target not in self.ids:
                    fail(f"{where}: $ref {v!r} is not a whole v3 document schema with a generated validator")
                self.refs.add(target)
                out["$ref"] = target
            elif k == "properties":
                out[k] = {p: self.compile(sub, base, f"{where}/properties/{p}") for p, sub in v.items()}
            elif k == "allOf":
                out[k] = [self.compile(sub, base, f"{where}/allOf/{i}") for i, sub in enumerate(v)]
            elif k in ("not", "contains", "if", "then", "else"):
                out[k] = self.compile(v, base, f"{where}/{k}")
            else:
                out[k] = v
        return out

    def rule(self, sid: str):
        doc = self.srcs.get(sid)
        if doc is None:
            return None
        members = [m for m in doc.get("allOf", []) if isinstance(m, dict) and "if" in m]
        if "if" in doc:
            members.append({k: doc[k] for k in ("if", "then", "else") if k in doc})
        conds = [
            self.compile({k: m[k] for k in ("if", "then", "else") if k in m}, sid, f"{sid} allOf conditional")
            for m in members if is_discriminator(m)
        ]
        # Everything the layer does not compile may still evaluate members.
        # For unevaluatedProperties, count every member name it could
        # evaluate. Over-counting can only accept more, never refuse a valid
        # document.
        others = [m for m in doc.get("allOf", []) if not (isinstance(m, dict) and "if" in m and is_discriminator(m))]
        others += [{k: doc[k]} for k in APPLICATORS if k in doc and k != "allOf" and not (k in ("if", "then", "else") and is_discriminator(doc))]
        overlays = {}
        for p, sub in doc.get("properties", {}).items():
            if isinstance(sub, dict) and "$ref" in sub:
                rest = {k: v for k, v in sub.items() if k != "$ref" and k not in ANNOTATIONS}
                if rest:
                    overlays[p] = self.compile(rest, sid, f"{sid} properties/{p} (next to $ref)")
        if not conds and not overlays:
            return None
        rule = {"conditionals": conds, "overlays": overlays, "closed": None,
                "nonnull": sorted(p for p, sub in doc.get("properties", {}).items() if self.nonnull(sub, sid, set()))}
        if doc.get("unevaluatedProperties") is False or doc.get("additionalProperties") is False:
            names, patterns = set(doc.get("properties", {})), set(doc.get("patternProperties", {}))
            if all(self.reach(m, sid, names, patterns, set()) for m in others):
                rule["closed"] = {"props": sorted(names), "patterns": sorted(patterns)}
            else:
                print(f"write-conditional-layer: {sid}: unevaluatedProperties left to the generated validator "
                      "(a member it cannot resolve could evaluate any name)", file=sys.stderr)
        return rule

    def nonnull(self, s, base, seen) -> bool:
        """True only when s certainly refuses null. Unsure means False, which never refuses."""
        if not isinstance(s, dict):
            return s is False
        t = s.get("type")
        if t is not None:
            return "null" not in (t if isinstance(t, list) else [t])
        if "const" in s:
            return s["const"] is not None
        if "enum" in s:
            return None not in s["enum"]
        if any(self.nonnull(x, base, seen) for x in s.get("allOf", [])):
            return True
        if "$ref" in s:
            target = urljoin(base, s["$ref"])
            doc_id, _, frag = target.partition("#")
            node = self.srcs.get(doc_id)
            for part in [p for p in frag.split("/") if p]:
                node = node.get(part.replace("~1", "/").replace("~0", "~")) if isinstance(node, dict) else None
            if node is None or target in seen:
                return False
            return self.nonnull(node, doc_id, seen | {target})
        return False

    def reach(self, s, base, names, patterns, seen) -> bool:
        """Every member name s could evaluate, added to names/patterns. False if unknowable."""
        if not isinstance(s, dict):
            return isinstance(s, bool)
        names.update(s.get("properties", {}))
        patterns.update(s.get("patternProperties", {}))
        if "additionalProperties" in s or "unevaluatedProperties" in s and s["unevaluatedProperties"] is not False:
            return False
        if "$ref" in s:
            target = urljoin(base, s["$ref"])
            if "#" in target or target not in self.srcs:
                return False
            if target not in seen:
                seen.add(target)
                t = self.srcs[target]
                if not self.reach({k: v for k, v in t.items() if k in ("properties", "patternProperties", *APPLICATORS)}, target, names, patterns, seen):
                    return False
        for k in ("allOf", "anyOf", "oneOf"):
            if not all(self.reach(x, base, names, patterns, seen) for x in s.get(k, [])):
                return False
        for k in ("if", "then", "else"):
            if k in s and not self.reach(s[k], base, names, patterns, seen):
                return False
        return all(self.reach(x, base, names, patterns, seen) for x in s.get("dependentSchemas", {}).values())


def keys(doc: dict) -> dict:
    return {"props": sorted(doc.get("properties", {})), "patterns": sorted(doc.get("patternProperties", {}))}


def build(bundle: Path):
    ids, srcs = components(bundle), sources()
    c = Compiler(ids, srcs)
    rules = {sid: r for sid in sorted(ids) if (r := c.rule(sid))}
    refkeys = {sid: keys(srcs[sid]) for sid in sorted(c.refs)}
    return ids, rules, refkeys


# ---------------------------------------------------------------- zod

ZOD_EVAL = r"""
type Rule = { conditionals: any[]; overlays: Record<string, any>; closed: { props: string[]; patterns: string[] } | null; nonnull: string[] };
type Issue = { path: (string | number)[]; message: string };

const isObj = (v: unknown): v is Record<string, unknown> => v !== null && typeof v === 'object' && !Array.isArray(v);
const canon = (v: unknown): unknown => Array.isArray(v) ? v.map(canon)
  : isObj(v) ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, canon(v[k])])) : v;
const same = (a: unknown, b: unknown) => JSON.stringify(canon(a)) === JSON.stringify(canon(b));

function evaluate(s: any, v: unknown, path: (string | number)[], out: Issue[]): void {
  if (s.$ref !== undefined) {
    const r = byId(s.$ref).safeParse(v);
    if (!r.success) for (const i of r.error.issues) out.push({ path: [...path, ...(i.path as (string | number)[])], message: i.message });
  }
  if (s.const !== undefined && !same(v, s.const)) out.push({ path, message: `must be ${JSON.stringify(s.const)}` });
  if (s.enum !== undefined && !s.enum.some((e: unknown) => same(v, e))) out.push({ path, message: `must be one of ${JSON.stringify(s.enum)}` });
  if (typeof v === 'number') {
    if (s.minimum !== undefined && v < s.minimum) out.push({ path, message: `must be >= ${s.minimum}` });
    if (s.maximum !== undefined && v > s.maximum) out.push({ path, message: `must be <= ${s.maximum}` });
    if (s.exclusiveMinimum !== undefined && v <= s.exclusiveMinimum) out.push({ path, message: `must be > ${s.exclusiveMinimum}` });
    if (s.exclusiveMaximum !== undefined && v >= s.exclusiveMaximum) out.push({ path, message: `must be < ${s.exclusiveMaximum}` });
  }
  if (Array.isArray(v)) {
    if (s.maxItems !== undefined && v.length > s.maxItems) out.push({ path, message: `must have at most ${s.maxItems} items` });
    if (s.minItems !== undefined && v.length < s.minItems) out.push({ path, message: `must have at least ${s.minItems} items` });
    if (s.contains !== undefined && !v.some((x) => passes(s.contains, x))) out.push({ path, message: 'must contain a matching item' });
  }
  if (isObj(v)) {
    for (const k of s.required ?? []) if (!(k in v)) out.push({ path: [...path, k], message: `required: ${k}` });
    for (const [k, sub] of Object.entries(s.properties ?? {})) if (k in v) evaluate(sub, v[k], [...path, k], out);
  }
  for (const sub of s.allOf ?? []) evaluate(sub, v, path, out);
  if (s.not !== undefined && passes(s.not, v)) out.push({ path, message: 'must not match the excluded shape' });
  if (s.if !== undefined) {
    const branch = passes(s.if, v) ? s.then : s.else;
    if (branch !== undefined) evaluate(branch, v, path, out);
  }
}

function passes(s: any, v: unknown): boolean {
  const out: Issue[] = [];
  evaluate(s, v, [], out);
  return out.length === 0;
}

/** Member names a branch evaluates, for unevaluatedProperties. */
function evaluated(s: any, names: Set<string>, patterns: string[]): void {
  for (const k of Object.keys(s.properties ?? {})) names.add(k);
  if (s.$ref !== undefined) {
    const k = REFKEYS[s.$ref];
    for (const p of k.props) names.add(p);
    patterns.push(...k.patterns);
  }
  for (const sub of s.allOf ?? []) evaluated(sub, names, patterns);
}

function check(id: string, v: unknown): Issue[] {
  const rule: Rule = RULES[id];
  const out: Issue[] = [];
  if (!isObj(v)) return out;
  const names = new Set<string>(rule.closed?.props ?? []);
  const patterns = [...(rule.closed?.patterns ?? [])];
  for (const c of rule.conditionals) {
    const ok = passes(c.if, v);
    const branch = ok ? c.then : c.else;
    if (ok) evaluated(c.if, names, patterns);
    if (branch !== undefined) {
      evaluate(branch, v, [], out);
      evaluated(branch, names, patterns);
    }
  }
  for (const k of rule.nonnull) if (k in v && v[k] === null) out.push({ path: [k], message: `${k} must not be null` });
  for (const [k, sub] of Object.entries(rule.overlays)) if (k in v) evaluate(sub, v[k], [k], out);
  if (rule.closed) {
    const res = patterns.map((p) => new RegExp(p, 'u'));
    for (const k of Object.keys(v)) {
      if (!names.has(k) && !res.some((r) => r.test(k))) out.push({ path: [k], message: `${k} is not allowed here (unevaluatedProperties)` });
    }
  }
  return out;
}

const REGISTRY: Record<string, z.ZodType> = {};

function byId(id: string): z.ZodType {
  const s = REGISTRY[id];
  if (!s) throw new Error(`conditional layer: no validator registered for ${id}`);
  return s;
}

/** Called by zod.gen.ts for a schema a branch delegates to by $ref. */
export function register<T extends z.ZodType>(id: string, schema: T): T {
  REGISTRY[id] = schema;
  return schema;
}

/** Called by zod.gen.ts straight after each layered schema's generated definition. */
export function layer<T extends z.ZodType>(id: string, base: T) {
  if (!RULES[id]) throw new Error(`conditional layer: no rule for ${id}`);
  return register(id, z.intersection(base, z.unknown().superRefine((v, ctx) => {
    for (const i of check(id, v)) ctx.addIssue({ code: 'custom', path: i.path, message: i.message });
  })));
}
"""


def zod(bundle: Path, out_dir: Path) -> None:
    ids, rules, refkeys = build(bundle)
    gen_path = out_dir / "zod.gen.ts"
    lines = gen_path.read_text().split("\n")

    def definition(name: str) -> tuple[int, int]:
        heads = [i for i, l in enumerate(lines) if l.startswith(f"export const {name} = ")]
        if len(heads) != 1:
            fail(f"zod.gen.ts: expected one definition of {name}, found {len(heads)}")
        i = heads[0]
        for j in range(i, len(lines)):
            if (j == i or not lines[j].startswith((" ", "\t"))) and lines[j].rstrip().endswith(";"):
                return i, j
        fail(f"zod.gen.ts: cannot find the end of {name}")

    edits = []
    for sid in sorted({*rules, *refkeys}):
        name = "z" + ids[sid]
        i, j = definition(name)
        if sid in rules:
            edits.append((i, j, name, f"export const {name} = layer('{sid}', {name}$generated);"))
        else:
            edits.append((i, j, None, f"register('{sid}', {name});"))
    for i, j, name, after in sorted(edits, reverse=True):
        lines.insert(j + 1, after)
        if name:
            lines[i] = lines[i].replace(f"export const {name} = ", f"const {name}$generated = ", 1)
    imp = next((k for k, l in enumerate(lines) if l.startswith("import ") and "'zod'" in l), None)
    if imp is None:
        fail("zod.gen.ts has no zod import to follow")
    lines.insert(imp + 1, "import { layer, register } from './conditionals';")
    gen_path.write_text("\n".join(lines))

    out = [
        f"// {HEADER}",
        "//",
        "// The conditional layer's rules and evaluator. zod.gen.ts applies it; see",
        "// scripts/lib/write-conditional-layer.py for what it evaluates and why the",
        "// generated schemas cannot.",
        "",
        "import * as z from 'zod';",
        "",
        f"const RULES: Record<string, Rule> = {json.dumps(rules, indent=2, ensure_ascii=False)};",
        "",
        f"const REFKEYS: Record<string, {{ props: string[]; patterns: string[] }}> = {json.dumps(refkeys, indent=2, ensure_ascii=False)};",
        ZOD_EVAL,
    ]
    (out_dir / "conditionals.ts").write_text("\n".join(out))
    print(f"write-conditional-layer: zod — {len(rules)} schemas layered in place "
          f"({', '.join('z' + ids[s] for s in sorted(rules, key=lambda s: ids[s]))})")


# ---------------------------------------------------------------- pydantic

PY_EVAL = r'''

# --- Conditional layer -------------------------------------------------------
# Generated by scripts/lib/write-conditional-layer.py. See it for what this
# evaluates and why the generated models cannot.

import json as _json
import re as _re

from pydantic import TypeAdapter as _TypeAdapter
from pydantic import ValidationError as _ValidationError


def _canon(v):
    if isinstance(v, list):
        return [_canon(x) for x in v]
    if isinstance(v, dict):
        return {k: _canon(v[k]) for k in sorted(v)}
    return v


def _same(a, b):
    # JSON equality: 1 == 1.0, but True is not 1.
    if isinstance(a, bool) or isinstance(b, bool):
        return type(a) is type(b) and a == b
    return _json.dumps(_canon(a)) == _json.dumps(_canon(b))


def _evaluate(s, v, path, out):
    if "$ref" in s:
        try:
            _TypeAdapter(_LAYER_MODELS[s["$ref"]]).validate_json(_json.dumps(v), strict=True)
        except _ValidationError as e:
            for err in e.errors():
                out.append(("/".join(map(str, [*path, *err["loc"]])), err["msg"]))
    if "const" in s and not _same(v, s["const"]):
        out.append(("/".join(map(str, path)), f"must be {_json.dumps(s['const'])}"))
    if "enum" in s and not any(_same(v, e) for e in s["enum"]):
        out.append(("/".join(map(str, path)), f"must be one of {_json.dumps(s['enum'])}"))
    if isinstance(v, (int, float)) and not isinstance(v, bool):
        for k, bad, word in (("minimum", v.__lt__, ">="), ("maximum", v.__gt__, "<="),
                             ("exclusiveMinimum", v.__le__, ">"), ("exclusiveMaximum", v.__ge__, "<")):
            if k in s and bad(s[k]):
                out.append(("/".join(map(str, path)), f"must be {word} {s[k]}"))
    if isinstance(v, list):
        if "maxItems" in s and len(v) > s["maxItems"]:
            out.append(("/".join(map(str, path)), f"must have at most {s['maxItems']} items"))
        if "minItems" in s and len(v) < s["minItems"]:
            out.append(("/".join(map(str, path)), f"must have at least {s['minItems']} items"))
        if "contains" in s and not any(_passes(s["contains"], x) for x in v):
            out.append(("/".join(map(str, path)), "must contain a matching item"))
    if isinstance(v, dict):
        for k in s.get("required", []):
            if k not in v:
                out.append(("/".join(map(str, [*path, k])), f"required: {k}"))
        for k, sub in s.get("properties", {}).items():
            if k in v:
                _evaluate(sub, v[k], [*path, k], out)
    for sub in s.get("allOf", []):
        _evaluate(sub, v, path, out)
    if "not" in s and _passes(s["not"], v):
        out.append(("/".join(map(str, path)), "must not match the excluded shape"))
    if "if" in s:
        branch = s.get("then") if _passes(s["if"], v) else s.get("else")
        if branch is not None:
            _evaluate(branch, v, path, out)


def _passes(s, v):
    out = []
    _evaluate(s, v, [], out)
    return not out


def _evaluated(s, names, patterns):
    names.update(s.get("properties", {}))
    if "$ref" in s:
        names.update(_REFKEYS[s["$ref"]]["props"])
        patterns.extend(_REFKEYS[s["$ref"]]["patterns"])
    for sub in s.get("allOf", []):
        _evaluated(sub, names, patterns)


def _layer_check(sid, data):
    if not isinstance(data, dict):
        return data
    rule, out = _LAYER_RULES[sid], []
    closed = rule["closed"] or {"props": [], "patterns": []}
    names, patterns = set(closed["props"]), list(closed["patterns"])
    for c in rule["conditionals"]:
        ok = _passes(c["if"], data)
        branch = c.get("then") if ok else c.get("else")
        if ok:
            _evaluated(c["if"], names, patterns)
        if branch is not None:
            _evaluate(branch, data, [], out)
            _evaluated(branch, names, patterns)
    for k in rule["nonnull"]:
        if k in data and data[k] is None:
            out.append((k, f"{k} must not be null"))
    for k, sub in rule["overlays"].items():
        if k in data:
            _evaluate(sub, data[k], [k], out)
    if rule["closed"]:
        for k in data:
            if k not in names and not any(_re.search(p, k) for p in patterns):
                out.append((k, f"{k} is not allowed here (unevaluatedProperties)"))
    if out:
        raise ValueError("; ".join(f"{p or '(root)'}: {m}" for p, m in out))
    return data


class _InheritRawKeyGuard:
    """Wraps a model's __pydantic_validator__ to refuse, on the raw input, keys
    that pydantic would otherwise discard unseen: the Python names of aliased
    fields, which the schema does not allow at that level."""

    def __init__(self, inner, title, names):
        self._inner, self._title, self._names = inner, title, frozenset(names)

    def _check(self, obj):
        if isinstance(obj, dict):
            bad = [k for k in obj if k in self._names]
            if bad:
                from pydantic_core import InitErrorDetails, PydanticCustomError
                raise _ValidationError.from_exception_data(self._title, [
                    InitErrorDetails(
                        type=PydanticCustomError("unevaluated_property", "{key} is not allowed here (unevaluatedProperties)", {"key": k}),
                        loc=(k,), input=obj[k],
                    ) for k in bad
                ])

    def validate_json(self, data, *args, **kwargs):
        try:
            parsed = _json.loads(data)
        except (TypeError, ValueError):
            parsed = None
        self._check(parsed)
        return self._inner.validate_json(data, *args, **kwargs)

    def validate_python(self, obj, *args, **kwargs):
        self._check(obj)
        return self._inner.validate_python(obj, *args, **kwargs)

    def validate_strings(self, obj, *args, **kwargs):
        self._check(obj)
        return self._inner.validate_strings(obj, *args, **kwargs)

    def __getattr__(self, name):
        return getattr(self._inner, name)


def _guard(cls, names):
    cls.__pydantic_validator__ = _InheritRawKeyGuard(cls.__pydantic_validator__, cls.__name__, names)
'''


def pydantic(bundle: Path, models: Path) -> None:
    ids, rules, refkeys = build(bundle)
    text = models.read_text()
    defined = set(re.findall(r"^class (\w+)\(", text, re.M))
    for sid in {*rules, *refkeys}:
        if ids[sid] not in defined:
            fail(f"no generated pydantic model {ids[sid]} for {sid}")
    if not re.search(r"^from pydantic import \([^)]*\bmodel_validator\b", text, re.M):
        text, n = re.subn(r"^from pydantic import \(\n", "from pydantic import (\n    model_validator,\n", text, count=1, flags=re.M)
        if n != 1:
            fail("models.py has no `from pydantic import (` block to extend")
    for sid in rules:
        name = ids[sid]
        method = (
            f"class {name}(BaseModel):\n"
            f"    @model_validator(mode='after')\n"
            f"    def _inherit_conditional_layer(self) -> Any:\n"
            f"        _layer_check({sid!r}, self.model_dump(mode='json', by_alias=True, exclude_unset=True))\n"
            f"        return self\n\n"
        )
        text, n = re.subn(rf"^class {name}\(BaseModel\):\n", method, text, count=1, flags=re.M)
        if n != 1:
            fail(f"models.py: class {name}(BaseModel) not found once")
    models_map = {s: ids[s] for s in sorted({*rules, *refkeys})}
    # Aliased fields whose Python name pydantic would silently discard, for
    # every closed layered class, plus any RootModel wrapping one.
    guards = {}
    for sid, rule in sorted(rules.items()):
        if not rule["closed"]:
            continue
        name = ids[sid]
        body = re.search(rf"^class {name}\(BaseModel\):\n(.*?)(?=^\S)", text, re.M | re.S)
        aliased = re.findall(r"^    (\w+): [^\n]*?(?:\n        [^\n]*?)*?alias='([^']+)'", body.group(1), re.M) if body else []
        names = sorted(py for py, alias in aliased if py != alias and py not in rule["closed"]["props"]
                       and not any(re.search(p, py) for p in rule["closed"]["patterns"]))
        if names:
            guards[name] = names
    for outer, inner in re.findall(r"^class (\w+)\(RootModel\[(\w+)\]\):", text, re.M):
        if inner in guards:
            guards[outer] = guards[inner]
    text = (
        text.rstrip("\n") + "\n" + PY_EVAL
        + f"\n\n_LAYER_RULES = {pformat(rules, sort_dicts=False, width=100)}\n"
        + f"\n_REFKEYS = {pformat(refkeys, sort_dicts=False, width=100)}\n"
        + "\n_LAYER_MODELS = {\n" + "".join(f"    {s!r}: {n},\n" for s, n in models_map.items()) + "}\n"
        + "\n" + "".join(f"_guard({n}, {v!r})\n" for n, v in guards.items())
    )
    models.write_text(text)
    print(f"write-conditional-layer: pydantic — {len(rules)} models layered ({', '.join(ids[s] for s in sorted(rules))}); "
          f"raw-key guard on {', '.join(f'{n} {v}' for n, v in guards.items()) or 'none'}")


if __name__ == "__main__":
    kind, bundle, target = sys.argv[1], Path(sys.argv[2]), Path(sys.argv[3])
    {"zod": zod, "pydantic": pydantic}[kind](bundle, target)
