#!/usr/bin/env python3
"""Write the $id → validator maps for both generated runtime validators:

  packages/sdk/src/zod/index.ts               schemasById  (Zod)
  packages/sdk-python/openinherit/models_by_id.py  MODELS_BY_ID (pydantic)

Each map is built from the OpenAPI bundle's own components (the component
whose $id is X), and every name it uses is checked against what the generated
file actually defines. A name that does not resolve is a hard failure, never
a silent skip: a missing entry would make the corpus gate report CANNOT
ANSWER, and a wrong one would validate against the wrong schema.

Usage: write-validator-indexes.py zod <openapi-bundled.yaml> <zod output dir>
       write-validator-indexes.py pydantic <openapi-bundled.yaml> <models.py>
"""
import re
import sys
from pathlib import Path

import yaml

HEADER = "This file is generated by scripts/generate-runtime-validators.sh — do not edit."


def pascal(key: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[^A-Za-z0-9]+", key) if p)


def resolve(bundle: Path, defined: set[str], prefix: str) -> list[tuple[str, str]]:
    schemas = yaml.safe_load(bundle.read_text())["components"]["schemas"]
    pairs, missing = [], []
    for key, body in schemas.items():
        sid = body.get("$id") if isinstance(body, dict) else None
        if not sid:
            continue
        name = prefix + pascal(key)
        if name in defined:
            pairs.append((sid, name))
        else:
            missing.append(f"no definition {name!r} for component {key!r} ($id {sid})")
    if missing:
        for m in missing:
            print(f"write-validator-indexes: {m}", file=sys.stderr)
        sys.exit(1)
    return sorted(pairs)


def zod(bundle: Path, out_dir: Path) -> None:
    gen = (out_dir / "zod.gen.ts").read_text()
    pairs = resolve(bundle, set(re.findall(r"^export const (z\w+)\b", gen, re.M)), "z")
    lines = [
        f"// {HEADER}",
        "",
        "import type * as z from 'zod';",
        "import * as schemas from './zod.gen';",
        "",
        "export * from './zod.gen';",
        "",
        "/** Every v3 document schema's validator, keyed by the schema's $id. */",
        "export const schemasById: Readonly<Record<string, z.ZodType>> = {",
        *[f"  '{sid}': schemas.{name}," for sid, name in pairs],
        "};",
        "",
    ]
    (out_dir / "index.ts").write_text("\n".join(lines))
    print(f"write-validator-indexes: zod — {len(pairs)} schemas mapped by $id")


def pydantic(bundle: Path, models: Path) -> None:
    pairs = resolve(bundle, set(re.findall(r"^class (\w+)\(", models.read_text(), re.M)), "")
    lines = [
        f'"""{HEADER}',
        "",
        "Every v3 document schema's generated type, keyed by the schema's $id.",
        "Most are pydantic models; a schema that is a bare enum generates as an",
        "Enum, so validate through pydantic.TypeAdapter rather than model_validate.",
        '"""',
        "",
        "from . import models",
        "",
        "MODELS_BY_ID: dict[str, type] = {",
        *[f'    "{sid}": models.{name},' for sid, name in pairs],
        "}",
        "",
    ]
    (models.parent / "models_by_id.py").write_text("\n".join(lines))
    print(f"write-validator-indexes: pydantic — {len(pairs)} models mapped by $id")


if __name__ == "__main__":
    kind, bundle, target = sys.argv[1], Path(sys.argv[2]), Path(sys.argv[3])
    {"zod": zod, "pydantic": pydantic}[kind](bundle, target)
