// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ValidateCatalogueDocumentData, ValidateCatalogueDocumentErrors, ValidateCatalogueDocumentResponses, ValidateDocumentData, ValidateDocumentErrors, ValidateDocumentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Validate an INHERIT estate document
 *
 * Accepts a complete INHERIT estate document and returns validation results
 * at three conformance levels: Schema Valid, Referentially Intact,
 * and Jurisdiction Complete.
 *
 */
export const validateDocument = <ThrowOnError extends boolean = false>(options: Options<ValidateDocumentData, ThrowOnError>) => (options.client ?? client).post<ValidateDocumentResponses, ValidateDocumentErrors, ThrowOnError>({
    url: '/validate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Validate an INHERIT catalogue document
 *
 * Accepts a complete INHERIT catalogue document and returns validation results.
 * Catalogues are dealer/platform asset collections distinct from individual
 * estates. The same three conformance levels apply.
 *
 */
export const validateCatalogueDocument = <ThrowOnError extends boolean = false>(options: Options<ValidateCatalogueDocumentData, ThrowOnError>) => (options.client ?? client).post<ValidateCatalogueDocumentResponses, ValidateCatalogueDocumentErrors, ThrowOnError>({
    url: '/validate/catalogue',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
